// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryPattern.Data.Context;

namespace RepositoryPattern.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RepositoryPattern.Domain.Entities.Song", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("kind_of_music")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("rating")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("view")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id")
                        .IsUnique();

                    b.ToTable("m_song");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Sơn Tùng MTP",
                            kind_of_music = "Pop",
                            name = "Lạc trôi",
                            rating = 4.6m,
                            view = 120000
                        },
                        new
                        {
                            id = 2,
                            author = "Lê Bảo Bình",
                            kind_of_music = "Nhạc Trẻ",
                            name = "Sai cách yêu",
                            rating = 4.2m,
                            view = 45000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
